version: "3.9"

services:
  web1:
    image: ghcr.io/anusha-3109/k8s-demo-app:v1.0.1
    container_name: webapp1
    environment:
      PORT: 3000
      APP_MESSAGE: "Hello from webapp1"
      APP_VERSION: "v1.0.1"
      MONGO_URL: mongodb://admin:password123@mongo:27017/demo?authSource=admin
    ports:
      - "3010:3000"
    depends_on:
      - mongo

  web2:
    image: ghcr.io/anusha-3109/k8s-demo-app:v1.0.2
    container_name: webapp2
    environment:
      PORT: 3000
      APP_MESSAGE: "Hello from webapp2"
      APP_VERSION: "v1.0.2"
      MONGO_URL: mongodb://admin:password123@mongo:27017/demo?authSource=admin
    ports:
      - "3020:3000"
    depends_on:
      - mongo

  web3:
    image: ghcr.io/anusha-3109/k8s-demo-app:v1.0.3
    container_name: webapp3
    environment:
      PORT: 3000
      APP_MESSAGE: "Hello from webapp3"
      APP_VERSION: "v1.0.3"
      MONGO_URL: mongodb://admin:password123@mongo:27017/demo?authSource=admin
    ports:
      - "3030:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
